# Generated by Django 4.2.3 on 2023-09-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drop',
        ),
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Drop',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
