# Generated by Django 4.2.3 on 2023-09-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField()),
                ('card_number', models.PositiveIntegerField(max_length=16)),
                ('holder', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('reject', 'Rejected')], max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
    ]
