# Generated by Django 4.2.3 on 2023-09-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_invoicedetail_invoicedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceDetail',
        ),
    ]
