# Generated by Django 4.2.3 on 2023-09-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.CharField(max_length=12),
        ),
    ]
