# Generated by Django 4.2.3 on 2023-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_payment_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='buyer',
            name='last_name',
            field=models.CharField(default='last', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
