# Generated by Django 4.2.3 on 2023-09-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_buyer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='name',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
