# Generated by Django 4.2.3 on 2023-09-17 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
    ]
