# Generated by Django 4.2.3 on 2023-09-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_product_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Enter Product Name', max_length=120, unique=True),
        ),
    ]
